# Generated by Django 4.2.7 on 2023-11-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechacompra', models.CharField(max_length=200)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('numeroasientos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpresasTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('rutas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('rol', models.IntegerField()),
                ('foto', models.CharField(max_length=255)),
                ('nombrecompleto', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=45)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origenciudad', models.CharField(max_length=255)),
                ('destinociudad', models.CharField(max_length=255)),
                ('duracionviaje', models.CharField(max_length=255)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_empresa', to='iTravelWeb.empresastransporte')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horasalida', models.CharField(max_length=250)),
                ('horallegada', models.CharField(max_length=250)),
                ('estado', models.IntegerField()),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios_boleto', to='iTravelWeb.boletos')),
            ],
        ),
        migrations.CreateModel(
            name='Choferes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choferes_bus', to='iTravelWeb.buses')),
            ],
        ),
        migrations.AddField(
            model_name='buses',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses_empresa', to='iTravelWeb.empresastransporte'),
        ),
        migrations.AddField(
            model_name='boletos',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_bus', to='iTravelWeb.buses'),
        ),
        migrations.AddField(
            model_name='boletos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_usuario', to='iTravelWeb.usuario'),
        ),
    ]
