# Generated by Django 4.2.7 on 2023-11-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iTravelWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
